name: Import foD results to GitHub

on: [workflow_dispatch]

jobs:
  FoD-Import:
    runs-on: windows-latest

    steps:
      - name: Check Out Source Code # We don't need source code, but upload-sarif action wants a git repo
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Export results to GitHub-optimized SARIF
        uses: fortify/gha-export-vulnerabilities@v1
        with:
          fod_base_url: https://ams.fortify.com/
          fod_tenant: ${{ secrets.FOD_TENANT }}
          fod_user: ${{ secrets.FOD_USER }}
          fod_password: ${{ secrets.FOD_PAT }}
          fod_release_id: ${{ secrets.FOD_RELEASE_ID }}
      - name: Import results to GitHub Security Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./gh-fortify-sast.sarif
